const FETCH_USERS = 'FETCH_USERS'
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

const ADD_USER = 'ADD_USER'
const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
const ADD_USER_FAILURE = 'ADD_USER_FAILURE'

const DELETE_USER = 'DELETE_USER'
const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

const UPDATE_USERNAME='UPDATE_USERNAME'
const UPDATE_USERNAME_SUCCESS='UPDATE_USERNAME_SUCCESS'
const UPDATE_USERNAME_FAIL='UPDATE_USERNAME_FAIL'

export default {
    FETCH_USERS,FETCH_USERS_SUCCESS,FETCH_USERS_FAILURE,
    ADD_USER,ADD_USER_SUCCESS,ADD_USER_FAILURE,
    DELETE_USER,DELETE_USER_SUCCESS,DELETE_USER_FAILURE,
    UPDATE_USERNAME,UPDATE_USERNAME_SUCCESS,UPDATE_USERNAME_FAIL
}